# Generated by Django 4.1.1 on 2022-09-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nme', models.CharField(max_length=25)),
                ('img', models.ImageField(upload_to='pix')),
                ('des', models.TextField()),
            ],
        ),
    ]
